---
- name: Configure simulated on-premises database tier
  hosts: db
  become: yes
  roles:
    - postgres

- name: Configure simulated on-premises application tier
  hosts: app
  become: yes
  roles:
    - app

- name: Configure simulated on-premises web ingress tier
  hosts: web
  become: yes
  roles:
    - nginx
